#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t bliss"

echo "======================================="
echo "               BlissRoms               "
echo "======================================="

$L "Welcome to BlissRoms `getprop ro.build.version.release` / Bliss-getprop ro.bliss.version";
